name: Blog CI/CD Pipeline to AWS with Docker Hub

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build-and-push:
    name: Build Docker Image, Push to Docker Hub
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: haze21/blog-frontend
      IMAGE_TAG: dev-${{ github.run_number }}  
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Clone ArgoCD repository
        uses: actions/checkout@v3
        with:
          repository: Hazetech21/Argo-CD
          token: ${{ secrets.CHECKOUT_TOKEN }}  
          path: blog

      - name: Update ArgoCD deployment.yaml
        run: |
          sed -i "s|image: .*$|image: $IMAGE_NAME:$IMAGE_TAG|g" blog/blog/deployment.yaml

      - name: Commit and push changes to ArgoCD repo
        run: |
          cd blog
          git config --global user.email "hazetech21@gmail.com"
          git config --global user.name "Hazetech21"
          git add blog/deployment.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push